import { Suspense } from 'react'
import Header from './components/Header/Header'
import './globals.css'
import { Inter } from 'next/font/google';
import {  } from "module";
import Loading from './loading';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header/>
          <Suspense fallback={<Loading/>}>
            {children}
          </Suspense>
      </body>
    </html>
  )
}
